### ISSUE TITLE
Can you provide more details...

### ISSUE THREAD

**Issue by CobraCalle** [NonDay/FreeSR#2]
Hello,

can you provide some informations about how to convert wav-samples from speakers to the files required for registring speakers?

My application can provide wav-files for the different users, and I would like to automate the registration steps inside the application...

Thanks a lot

Carl

**Comment by nonday** [comment]
If you don't know whose the wav-file is, you can register a wav-file for user label A or B or C ...... But it will lead that wav-files of the one speaker were registered for many different speaker.

**Comment by CobraCalle** [comment]
Sorry... I had another look at your sample... as I understand, I do register a user with a wav-sample. But what are the other paramters?

ret = spk.RegisterSpeaker(signal, "english", "english.iv");

signal is the wav-sample... but what is "english"? Is that the name of the Speaker? And can I provide more than one sample per speaker by calling that method for every sample? Or do I have to user unique speakernames (like "UserA_Sample1", "UserA_Sample2" and so on)?

And what is the third parameter? And why is that file called "english.iv"... do I need that file per speaker? Does that work with german speakers to, of do I need a "german.iv", and if yes where do I get those?

Thank you very much for your help

Carl

**Comment by nonday** [comment]
ret = spk.RegisterSpeaker(signal, "english", "english.iv");
"english" is that the name of the Speaker; "english.iv" is a model file for a speaker.
If you use more than one sample per speaker, you can use this:
ret =spk.RegisterSpeaker(std::vector<std::string> fpaths, std::string speaker_name, std::string speaker_model = "")
you can also cancat all the wav sample to one wav, or put them to signal.

**Comment by CobraCalle** [comment]
Thanks for your reply... but from where du I get the iv-file? Or ist that file create in the registration step?

**Comment by nonday** [comment]
Yes,you are right.
