### ISSUE TITLE
Externals for P/Invoke from .NET

### ISSUE THREAD

**Issue by CobraCalle** [NonDay/FreeSR#3]
Hi,

I would like to use FreeSR from .NET by P/Invoking the required methods. Because classes / class methods cannot be invoked directly, I`ve tried to build a wrapper dll around it, like this:

`extern "C" SpeakerRecognizer * CreateSpeakerRecognizer(int smapleRate)
{
	return new SpeakerRecognizer(smapleRate);
}

extern "C" void DisposeSpeakerRecognizer(SpeakerRecognizer * speakerRecognizer)
{
	delete speakerRecognizer;
}

extern "C" bool InitSpeakerRecognizer(SpeakerRecognizer * speakerRecognizer)
{
	return speakerRecognizer->Init();
}

extern "C" double VerifySpeakerByData(SpeakerRecognizer * speakerRecognizer, std::vector<double> signal_1, std::vector<double> signal_2)
{
	return speakerRecognizer->VerifySpeaker(signal_1, signal_2);
}

extern "C" double VerifySpeakerByFile(SpeakerRecognizer * speakerRecognizer, char* fpath_1, char* fpath_2)
{
	return speakerRecognizer->VerifySpeaker(fpath_1, fpath_2);
}

extern "C" bool RegisterSpeakerByData(SpeakerRecognizer * speakerRecognizer, double* signal, int signalLength, char* speaker_name, char* speaker_model)
{
	try
	{
		std::vector<double> signal2(signal, signal + signalLength);

		return speakerRecognizer->RegisterSpeaker(signal2, speaker_name, speaker_model);
	}
	catch (std::exception ex)
	{
		return false;
	}
}

extern "C" bool RegisterSpeakerByFile(SpeakerRecognizer * speakerRecognizer, char* fpath, char* speaker_name, char* speaker_model)
{
	try
	{
		std::string fpath2(fpath);
		std::string speaker_name2(speaker_name);
		std::string speaker_model2(speaker_model);

		return speakerRecognizer->RegisterSpeaker(fpath2, speaker_name2, speaker_model2);
	}
	catch (std::exception ex)
	{
		return false;
	}
}

extern "C" char* RecognizeSpeakerByData(SpeakerRecognizer * speakerRecognizer, std::vector<double> signal)
{
	std::string result = speakerRecognizer->RecognizeSpeaker(signal);
	int len = result.size();

	char* result2 = new char[len + 1];

	std::copy(result.begin(), result.end(), result2);
	result2[len] = '\0';

	return result2;
}

extern "C" char* RecognizeSpeakerByFile(SpeakerRecognizer * speakerRecognizer, char* fpath)
{
	std::string result = speakerRecognizer->RecognizeSpeaker(fpath);
	int len = result.size();

	char* result2 = new char[len + 1];

	std::copy(result.begin(), result.end(), result2);
	result2[len] = '\0';

	return result2;
}

extern "C" double GetConfidence(SpeakerRecognizer * speakerRecognizer)
{
	return speakerRecognizer->GetConfidence();
}`

Creating an instance of speakerrecognizer and calling init on it, works like expected. But I have no luck calling RegisterSpeaker... everything I`ve tried results in an access violation or bad allocation. I've tries to pass a wav-file, a wav-file without headers and passing the raw samples (16000, 1 channel) as double array...

Would it be possible to include the methods for direct p/invoke directly to the library (and the used wav-files from the example ti the repo)?

Thanks a lot

Carl

**Comment by nonday** [comment]
Firstly, let it works in c++. Then try it in .net.

**Comment by CobraCalle** [comment]
I dont´t think that this will make any difference... I can debug the call from the .net-side... the paramters are looking good...

For example:
speakerRecognizer->RegisterSpeaker(fpath2, speaker_name2, speaker_model2);

fpath2 is a valid path to a wave file (16bit, 1 channel, 16000 samples per second)
speaker_name2 is "Carl"
speaker_model2 is ""

Result: Access Violation (same result if the file does only contain the raw smaples (without RIFF header))

No matter if I call it though .net / pinvoke oder from a command line tool

At the moment I think that the data I`m passing to the method is not correct, but I cannot find any information about the required format (Bits per sample, channels, samples per second).

Another question I`m asking myself is... why is the data stored in an array of doubles? does that mean 32bits per sample is required, or do you user 16bits per sample and just just double instead of float? The "english.wav" unter examples is 16 bits per sample...

Would it be possible to upload the wav files uses in the examples? With those files I could reproduce the exact sample in the first step.

thanks a lot

carl

**Comment by nonday** [comment]
The wav file should contains wav-header(with RIFF header), and it's 16bit signed int,1 channels, 16k sample rate.
About the data type, you can convert 16bit signed int to double.

**Comment by CobraCalle** [comment]
Thank you for the clearification...

Here is a screenshot from the debugger before calling "RegisterSpeaker" including the parameter value (the wav-file is 16 Bit / 1 Channel / 16k Samplerate):
![image](https://user-images.githubusercontent.com/6218368/96088880-5bb78780-0ec6-11eb-8146-f208b043ef41.png)

This results in an access violation... do you have any clue what could be the problem?

Using the RegisterSpeaker method with vector of double results in an access violation too (not matter with or without RIFF header).

Of course I know that I can convert int16 to double... but normally this conversion has to be done like this:
`                var wavData = new double[wavDataLength];
                var smapleBuffer = new byte[sizeof(Int16)];

                for (int index = 0; index < wavDataLength; index++)
                {
                    audioStream.Read(smapleBuffer, 0, smapleBuffer.Length);

                    wavData[index] = (BitConverter.ToInt16(smapleBuffer) / (double)Int16.MaxValue);
                }`

Based on your last comment I tried...
                    wavData[index] = (double)BitConverter.ToInt16(smapleBuffer);

But that does not change anything... perhaps it is a mismatch in calling convention or encoding when calling in your library... is ist ANSI or Unicode? And is it Cdecl or Stdl?

**Comment by nonday** [comment]
Hi, @CobraCalle what's the environment of yours? The library is generated by vs2015/X64/Release.

**Comment by CobraCalle** [comment]
my wrapper-dll is build with vs2019 on windows 10 on an x64 machine (currently in debug)

In the mean time I've tried this...
![image](https://user-images.githubusercontent.com/6218368/96091789-50fef180-0eca-11eb-899d-24c51158f6bf.png)
...and even this results in an "A heap has been corrupted" Exception.

I this, I have to change something in the project properties of my c++ projekt... but I´m not familar enough with c++ to know what could be the problem...

**Comment by CobraCalle** [comment]
![image](https://user-images.githubusercontent.com/6218368/96092253-ee5a2580-0eca-11eb-8751-c69982399796.png)
![image](https://user-images.githubusercontent.com/6218368/96092298-fa45e780-0eca-11eb-8906-6b4f183aac20.png)
![image](https://user-images.githubusercontent.com/6218368/96092326-0336b900-0ecb-11eb-8975-2ec73266f7dd.png)

**Comment by nonday** [comment]
Try again in x64/Release. It will not work in Debug.

**Comment by CobraCalle** [comment]
WOW... now I can use the file based methods... why the wrapper has to be compiled in release is a miracle to me, but OK... cool...

...but ( :-) ) I would like to use the methods with double vectors... those calls still throw an access violation exception.

just to be clear... thos methods have to be feeded with the complete file content (including RIFF header) - correct? So just read int16s from the file, cast them to double and pass the result to the method? could that realy be correct?

**Comment by CobraCalle** [comment]
Sorry.. forget that... I`ve tried to pass NULL for the model file... chaned that to string, now it works

**Comment by CobraCalle** [comment]
Thank you soooo much! It works like a charm... ways better than the previously solution 👍💪
