### ISSUE TITLE
looking for android port

### ISSUE THREAD

**Issue by GeorvityLabs** [NonDay/FreeSR#4]

**Comment by nonday** [comment]
android lib updated now @GeorvityLabs

**Comment by GeorvityLabs** [comment]
@nonday thank you. 
Can you make it gradle project?  So that it can run on android studio?

**Comment by GeorvityLabs** [comment]
> android lib updated now @GeorvityLabs

Is there a UI for the android SR project?
Hope you can make it gradle project + include an example UI to use the SR features.

**Comment by GeorvityLabs** [comment]
> android lib updated now @GeorvityLabs

could we get an android UI 

> android lib updated now @GeorvityLabs

if you had an APK to test, that would be great too.
