### ISSUE TITLE
can we get an android apk for testing?

### ISSUE THREAD

**Issue by GeorvityLabs** [NonDay/FreeSR#5]
could you make a seperate gradle project , so that we can build the apk and use the project inside Android Studio?

**Comment by nonday** [comment]
@GeorvityLabs 
lingk: https://share.weiyun.com/U5JqXQye 
password: taiw5h

**Comment by nonday** [comment]
@GeorvityLabs 
lingk: https://share.weiyun.com/U5JqXQye 
password: taiw5h

**Comment by GeorvityLabs** [comment]
Can't download it.

Can you upload it on Dropbox , Mediafire or MEGA?

**Comment by nonday** [comment]
give me a email?

**Comment by GeorvityLabs** [comment]
Ok cool..
My email id : georvityofficial@gmail.com

**Comment by nonday** [comment]
Have send it.

**Comment by GeorvityLabs** [comment]
Thank you!

**Comment by nonday** [comment]
[freesrexample.zip](https://github.com/nonday/FreeSR/files/7668455/freesrexample.zip)

upload the export zip here
